try{
    let a = 10;
let b = 4;
let c = a+b;
console.log(a);
console.log(b);
console.log(c);
console.log(a+c);
console.log(a+d);
}
catch(err){
    console.log(err);
}
